### ISSUE TITLE
What is the license which applies to this repository?

### ISSUE THREAD

**Issue by ifraixedes** [rafael-santiago/pig#1]
Hi there,

Thanks so much for this work.

Do you have any license in mind for this work? it will be great for people what they can do with this if they think in something.

Thanks

**Comment by rafael-santiago** [comment]
Hello,

You are welcome.

Currently I am using GPL v2.

Best regards

**Comment by rafael-santiago** [comment]
I have just added a new file (COPYING) in the root directory specifying the current chosen license.  

Thanks for your suggestion.
