### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [rafael-santiago/pig#2]
I would like to point out that identifiers like "[`_PIG_MKPKT_H`](https://github.com/rafael-santiago/pig/blob/bc6faa70b52e3892e7460e736efd9c712893a724/src/mkpkt.h#L8)" and "[`_PIG_NETMASK_H`](https://github.com/rafael-santiago/pig/blob/4038c70e2b6b7d8593172e8bf6459aca9af4a15a/src/netmask.h#L8)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by rafael-santiago** [comment]
I think your suggestion is pretty nice. Now this [commit](https://github.com/rafael-santiago/pig/commit/4a8857fa24cadba8009c047e8e01a42f6de2ab36) implements the improvement.

I decided for keeping the include guard prefixed with the project name (based on [google code style](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#The__define_Guard)) but all leading underscores were stripped.

What do you think about?

Thanks!

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/rafael-santiago/pig/commit/4a8857fa24cadba8009c047e8e01a42f6de2ab36#diff-ff666498ed19394d8914aad96fcf8bb2L1).
