### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [rafael-santiago/pig#3]
[The function "printf"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
How do you think about to delete its call from your function "[sigint_watchdog](https://github.com/rafael-santiago/pig/blob/f16cdb473cebd6c490c032b7b7a84bc937a9899d/src/main.c#L58)"?

**Comment by rafael-santiago** [comment]
It is a good point and a good idea. Your fix suggestion was implemented in this [commit](https://github.com/rafael-santiago/pig/commit/2b6a8f34c849e4e632edbdad1951cb98ca815b9a).

Thank you!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/rafael-santiago/pig/commit/2b6a8f34c849e4e632edbdad1951cb98ca815b9a).
